apiVersion: apps/v1
kind: Deployment
metadata:
  name: sigil-okteto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sigil-okteto
  template:
    metadata:
      labels:
        app: sigil-okteto
    spec:
      containers:
      - image: okteto.dev/sigil-okteto:latest
        name: sigil-okteto
        ports:
        - containerPort: 8080
