apiVersion: v1
kind: Service
metadata:
  name: sigil-okteto
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "sigil-okteto"
    port: 8080
  selector:
    app: sigil-okteto
